project:
  type: website
  output-dir: docs

website:
  title: "Vincent Gaul"
  site-url: https://vincentgaul.github.io
  description: "Biochemist bridging life science and data science"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Projects"
        href: projects.html
  page-footer:
    left: "Â© Copyright 2024 Vincent Gaul. All rights reserved."

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true



